name: build

on: [push]

jobs:
  build_mac:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: MacOS

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: xcodebuild -scheme display_switch -configuration release -derivedDataPath .build build

  build_windows:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: Windows

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose
      - uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            Windows/target/release/display_switch.exe
            MacOS/.build/Build/Products/release/display_switch
            README.md
